<a href="https://colab.research.google.com/github/ib1905/MIPT_Python_professional_development_program/blob/main/Python_lesson_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([3, 4, 5]) # converting a list into an array
print(a)
print(type(a))

[3 4 5]
<class 'numpy.ndarray'>


In [3]:
numbers = [1.2] * 10000
print(numbers[0:10])

[1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2]


In [7]:
%%timeit
# tracking time with a Python list
squares = [x ** 2 for x in numbers]
#print(squares[0:10])

1000 loops, best of 5: 793 µs per loop


In [8]:
np_numbers = np.array(numbers)
np_numbers

array([1.2, 1.2, 1.2, ..., 1.2, 1.2, 1.2])

In [9]:
%%timeit
# tracking time with a numpy array
np_squares = np_numbers ** 2
#print(np_squares)

The slowest run took 41.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 4.04 µs per loop


In [14]:
a = np.array([3, 4, 5])
a[1]

4

In [15]:
a[1] = 3
a

array([3, 3, 5])

In [16]:
a[1] = 3.5 # implicit conversion, so there is only one type of data in the array
a

array([3, 3, 5])

In [20]:
a = np.array(a).astype(np.float64) # explicit conversion to a float type of data
print(a)

[3. 3. 5.]


In [21]:
b = np.array([5, 5, 5])
b.dtype

dtype('int64')

In [22]:
text = np.array(['one', 'two', 'three'])
text

array(['one', 'two', 'three'], dtype='<U5')

In [23]:
mixed = np.array([1, True, 3.5, 'Hello'])
mixed

array(['1', 'True', '3.5', 'Hello'], dtype='<U32')

In [24]:
c = np.array([1, 2, 3])
print(c)

[1 2 3]


In [25]:
d = np.append(c, 6)
print(c)
print(d)

[1 2 3]
[1 2 3 6]


In [27]:
d2_array = np.array([[2, 3], [4, 5]])
d2_array

array([[2, 3],
       [4, 5]])

In [44]:
d3_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d3_array)

print(np.shape(d3_array))
print(np.size(d3_array))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
8


In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([9, 8, 7, 6])
a + b # ONLY for arrays with equal shapes

array([10, 10, 10, 10])

In [35]:
a + 1

array([2, 3, 4, 5])

In [36]:
a < b

array([ True,  True,  True,  True])

In [46]:
print(np.any(a)) # any() function returns True if at least one item in a Numpy array evaluates to True
print(np.all(a)) # all() function returns True only if all items in a Numpy array evaluate as True

True
True


In [47]:
print(a)
a.sum(), a.prod(), a.max(), a.mean()

[1 2 3 4]


(10, 24, 4, 2.5)

In [49]:
x = np.random.normal(size = 100)
x

array([-0.71193809, -0.01881881, -0.99385768, -0.96783198, -0.76748886,
       -0.64150593, -0.37307922,  1.4616204 , -0.46559801,  0.01113766,
        2.90993022, -1.23259443, -1.84681375,  0.87495738,  0.81776214,
       -0.04581779,  0.35833937, -0.09538134,  1.88860931, -0.50097837,
        0.41911656,  1.13661648, -0.58203468,  0.18789833, -1.09054669,
        0.27480085, -0.62416391, -0.61850062,  0.52545253,  0.72958267,
       -1.51234757, -0.50766487,  0.69981713,  0.36806913,  1.83483926,
        1.06960145,  0.02468357,  0.23755421,  0.14132495,  0.20942118,
        1.17453484,  1.70798458, -1.5049027 , -1.97018355,  1.01993161,
        0.67311208, -0.18575578,  1.33847658, -0.61247614,  1.63769752,
       -1.3127953 ,  0.07851497,  0.31374307, -0.73047804, -0.56375668,
       -0.20605686, -0.6908208 ,  0.11873378, -0.94532534,  0.96873259,
        0.25174644,  0.63610932,  0.74418476, -2.14338513, -0.31536772,
       -0.16120721,  0.02210039,  2.19662719,  1.10893978,  0.46

In [56]:
x.mean()
#np.sqrt(x), np.exp(x), np.log(x)

0.0783602698012782

In [57]:
np.sort(x) # as a method; in case we need a function: sort(x)

array([-2.14338513, -2.05194242, -1.97018355, -1.84681375, -1.70470477,
       -1.51234757, -1.5049027 , -1.3127953 , -1.23259443, -1.10515117,
       -1.09054669, -0.99385768, -0.98471382, -0.96783198, -0.94532534,
       -0.91134552, -0.9005979 , -0.8864158 , -0.83321056, -0.76748886,
       -0.73047804, -0.7141133 , -0.71193809, -0.6908208 , -0.64150593,
       -0.62416391, -0.61850062, -0.61247614, -0.58203468, -0.56375668,
       -0.54923183, -0.50766487, -0.50097837, -0.46559801, -0.41514214,
       -0.37307922, -0.33390678, -0.32491365, -0.31673694, -0.31536772,
       -0.23802883, -0.20605686, -0.20345087, -0.18575578, -0.16120721,
       -0.10322548, -0.09538134, -0.04581779, -0.01881881,  0.01113766,
        0.02210039,  0.02468357,  0.07851497,  0.11873378,  0.13180759,
        0.14132495,  0.18789833,  0.19954809,  0.20942118,  0.23755421,
        0.25174644,  0.27480085,  0.31374307,  0.35833937,  0.36201631,
        0.36806913,  0.37245121,  0.41911656,  0.46315816,  0.52

In [58]:
print(a, b)
np.vstack((a, b)) # combining arrays

[1 2 3 4] [9 8 7 6]


array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [60]:
np.hstack((a, b))

array([1, 2, 3, 4, 9, 8, 7, 6])

In [61]:
np.hsplit(a, [3, 6])

[array([1, 2, 3]), array([4]), array([], dtype=int64)]

In [65]:
a = np.linspace(0, 1, 11) # splitting an array within the range 0-1 and divide in 11 parts
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [66]:
a[3:9:2] # indexing and defining a step

array([0.3, 0.5, 0.7])

In [68]:
a[3:9:2] = 0 # assigning '0' to the specified range with the step of 2
a

array([0. , 0.1, 0.2, 0. , 0.4, 0. , 0.6, 0. , 0.8, 0.9, 1. ])

In [70]:
print(a)
b = np.delete(a, [1, 2])
print(b)

[0.  0.1 0.2 0.  0.4 0.  0.6 0.  0.8 0.9 1. ]
[0.  0.  0.4 0.  0.6 0.  0.8 0.9 1. ]


In [72]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 1], [1, 0]])
a @ b # matrix multiplication

array([[2, 1],
       [4, 3]])

In [73]:
np.matrix(a) * np.matrix(b)

matrix([[2, 1],
        [4, 3]])

In [74]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
I.reshape(16)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [76]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
for row in I:
  print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


In [82]:
def f(i, j):
  print(i)
  print(j)
  return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
